export const enum Paths {
  Example = 'example',
  Startup = 'startup',
  Onboarding = 'onboarding',
  Register = 'register',
  Login = 'login',
  Splash = 'splash',
  Home = 'home',
  Gorev = 'gorev',
  Gorev_Listesi = 'gorev_listesi',
  Leaderboard = 'leaderboard',
  Settings = 'settings',
  Empty = 'empty',
  VideoRecord = 'video_record',
  PdfViewer = 'pdf_viewer',
}
